name: Документация по OpenCart
description: Документация для скрипта OpenCart от opencart.com
url: https://opencart.name
baseurl: https://opencart.github.io/
repository: https://github.com/ruOpenCart/ruopencart.github.io
markdown: kramdown
permalink: pretty
